gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is Birch.\p"
	.string "But everyone calls me the Pokémon\n"
	.string "Professor.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "And this…is what we call a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as Pokémon.\p"
	.string "We humans live alongside Pokémon,\n"
	.string "at times playing together as friends,\l"
	.string "and at times helping one another out.\p"
	.string "And sometimes, we just like to have fun\n"
	.string "battling others like us!\p"
	.string "But as close as we are, we don't\n"
	.string "know everything about Pokémon.\p"  
	.string "In fact, there are many, many\n"
	.string "mysteries surrounding Pokémon.\p"
	.string "I do research to try to unravel those\n"
	.string "Pokémon mysteries.\l"
	.string "But that's enough about me!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "What about you?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "Will you give me your name, too?$"

gText_Birch_SoItsPlayer::
	.string "So you're {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah… I see.\p"
	.string "You're THAT {PLAYER}{KUN}!\p"
	.string "You're the one who's moving to\n"
	.string "Littleroot Town, where I live!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Are you ready?\p"
	.string "Your very own adventure is now about\n"
	.string "to unfold.\p"
	.string "Be courageous and leap into the world\n"
	.string "of Pokémon where dreams, adventures,\l"
	.string "and friendships await!\p"
	.string "I expect we'll be meeting again soon.\n"
	.string "Come see me in my Pokémon Lab!\p"
	.string "$"
